#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  6 14:11:09 2017

@author: guido
"""
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import tensorflow as tf
import os
import glob # for bulk file import

os.chdir("/home/guido/NEU")

imgpathsTrash = glob.glob("./GitHub/Image_Analysis_in_Python/images/trash/*.JPEG")
imgpathsTrash = imgpathsTrash[0] 

img = mpimg.imread(imgpathsTrash)
print img.shape 

img_tf = tf.Variable(img)



init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

im = sess.run(img_tf)

fig = plt.figure()
fig.add_subplot(1,2,1)
plt.imshow(im)
fig.add_subplot(1,2,2)
plt.imshow(img)
plt.show()